# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banktransaction.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'banktransaction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x62\x61nktransaction.proto\x12\x0f\x62\x61nktransaction\"\x81\x01\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfrom_user\x18\x02 \x01(\t\x12\x0f\n\x07to_user\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x10\n\x08ts_epoch\x18\x07 \x01(\x03\"`\n\x18\x43reateTransactionRequest\x12\x11\n\tfrom_user\x18\x01 \x01(\t\x12\x0f\n\x07to_user\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\"\x1b\n\rTransactionId\x12\n\n\x02id\x18\x01 \x01(\t\"E\n\x0fTransactionList\x12\x32\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x1c.banktransaction.Transaction\"\x07\n\x05\x45mpty\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t2\xd0\x02\n\x12TransactionService\x12\\\n\x11\x43reateTransaction\x12).banktransaction.CreateTransactionRequest\x1a\x1c.banktransaction.Transaction\x12N\n\x0eGetTransaction\x12\x1e.banktransaction.TransactionId\x1a\x1c.banktransaction.Transaction\x12T\n\x17ListTransactionsForUser\x12\x17.banktransaction.UserId\x1a .banktransaction.TransactionList\x12\x36\n\x04Ping\x12\x16.banktransaction.Empty\x1a\x16.banktransaction.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banktransaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=43
  _globals['_TRANSACTION']._serialized_end=172
  _globals['_CREATETRANSACTIONREQUEST']._serialized_start=174
  _globals['_CREATETRANSACTIONREQUEST']._serialized_end=270
  _globals['_TRANSACTIONID']._serialized_start=272
  _globals['_TRANSACTIONID']._serialized_end=299
  _globals['_TRANSACTIONLIST']._serialized_start=301
  _globals['_TRANSACTIONLIST']._serialized_end=370
  _globals['_EMPTY']._serialized_start=372
  _globals['_EMPTY']._serialized_end=379
  _globals['_USERID']._serialized_start=381
  _globals['_USERID']._serialized_end=401
  _globals['_TRANSACTIONSERVICE']._serialized_start=404
  _globals['_TRANSACTIONSERVICE']._serialized_end=740
# @@protoc_insertion_point(module_scope)
