# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: userprofile.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'userprofile.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11userprofile.proto\x12\x0buserprofile\"=\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\",\n\x08UserList\x12 \n\x05users\x18\x01 \x03(\x0b\x32\x11.userprofile.User\"\x07\n\x05\x45mpty2}\n\x0bUserService\x12\x36\n\x07GetUser\x12\x18.userprofile.UserRequest\x1a\x11.userprofile.User\x12\x36\n\tListUsers\x12\x12.userprofile.Empty\x1a\x15.userprofile.UserListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userprofile_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=34
  _globals['_USER']._serialized_end=95
  _globals['_USERREQUEST']._serialized_start=97
  _globals['_USERREQUEST']._serialized_end=122
  _globals['_USERLIST']._serialized_start=124
  _globals['_USERLIST']._serialized_end=168
  _globals['_EMPTY']._serialized_start=170
  _globals['_EMPTY']._serialized_end=177
  _globals['_USERSERVICE']._serialized_start=179
  _globals['_USERSERVICE']._serialized_end=304
# @@protoc_insertion_point(module_scope)
